# SPDX-FileCopyrightText: 2025 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.856898");
  script_version("2025-02-20T08:47:14+0000");
  script_cve_id("CVE-2024-50379", "CVE-2024-52317", "CVE-2024-54677");
  script_tag(name:"cvss_base", value:"5.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:N/A:N");
  script_tag(name:"last_modification", value:"2025-02-20 08:47:14 +0000 (Thu, 20 Feb 2025)");
  script_tag(name:"creation_date", value:"2025-01-09 05:00:04 +0000 (Thu, 09 Jan 2025)");
  script_name("openSUSE: Security Advisory for tomcat10 (SUSE-SU-2025:0033-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2025 Greenbone AG");
  script_family("SuSE Local Security Checks");

  script_xref(name:"Advisory-ID", value:"SUSE-SU-2025:0033-1");
  script_xref(name:"URL", value:"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/R2IT7I6R7IICWNFTQM2VQTVL5JMUZMA4");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'tomcat10'
  package(s) announced via the SUSE-SU-2025:0033-1 advisory.
Note: This VT has been deprecated and replaced by a Notus scanner based one.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"This update for tomcat10 fixes the following issues:

  Update to Tomcat 10.1.34

  * Fixed CVEs:

  * CVE-2024-54677: DoS in examples web application (bsc#1234664)

  * CVE-2024-50379: RCE due to TOCTOU issue in JSP compilation (bsc#1234663)

  * CVE-2024-52317: Request/response mix-up with HTTP/2 (bsc#1233435)

  * Catalina

  * Add: Add option to serve resources from subpath only with WebDAV Servlet
      like with DefaultServlet. (michaelo)

  * Fix: Add special handling for the protocols attribute of SSLHostConfig in
      storeconfig. (remm)

  * Fix: 69442: Fix case sensitive check on content-type when parsing request
      parameters. (remm)

  * Code: Refactor duplicate code for extracting media type and subtype from
      content-type into a single method. (markt)

  * Fix: Compatibility of generated embedded code with components where
      constructors or property related methods throw a checked exception. (remm)

  * Fix: The previous fix for inconsistent resource metadata during concurrent
      reads and writes was incomplete. (markt)

  * Fix: #780: Fix content-range header length. Submitted by Chenjp. (remm)

  * Fix: 69444: Ensure that the jakarta.servlet.error.message request attribute
      is set when an application defined error page is called. (markt)

  * Fix: Avoid quotes for numeric values in the JSON generated by the status
      servlet. (remm)

  * Add: Add strong ETag support for the WebDAV and default servlet, which can
      be enabled by using the useStrongETags init parameter with a value set to
      true. The ETag generated will be a SHA-1 checksum of the resource content.
      (remm)

  * Fix: Use client locale for directory listings. (remm)

  * Fix: 69439: Improve the handling of multiple Cache-Control headers in the
      ExpiresFilter. Based on pull request #777 by Chenjp. (markt)

  * Fix: 69447: Update the support for caching classes the web application class
      loader cannot find to take account of classes loaded from external
      repositories. Prior to this fix, these classes could be incorrectly marked
      as not found. (markt)

  * Fix: 69466: Rework handling of HEAD requests. Headers explicitly set by
      users will not be removed and any header present in a HEAD request will also
      be present in the equivalent GET request. There may be some headers, as per
      RFC 9110, section 9.3.2, that are present in a GET request that are not
      present in the equivalent HEAD request. (markt)

  * Fix: 69471: Log instances of CloseNowException caught by
      ApplicationDispatcher.invoke() at debug level r ...

  Description truncated. Please see the references for more information.");

  script_tag(name:"affected", value:"'tomcat10' package(s) on openSUSE Leap 15.6.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  script_tag(name:"deprecated", value:TRUE);

  exit(0);
}

exit(66);
