# SPDX-FileCopyrightText: 2015 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.703207");
  script_cve_id("CVE-2015-2684");
  script_tag(name:"creation_date", value:"2015-03-27 23:00:00 +0000 (Fri, 27 Mar 2015)");
  script_version("2024-01-19T05:06:16+0000");
  script_tag(name:"last_modification", value:"2024-01-19 05:06:16 +0000 (Fri, 19 Jan 2024)");
  script_tag(name:"cvss_base", value:"4.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:S/C:N/I:N/A:P");

  script_name("Debian: Security Advisory (DSA-3207)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2015 Greenbone AG");
  script_family("Debian Local Security Checks");

  script_xref(name:"Advisory-ID", value:"DSA-3207");
  script_xref(name:"URL", value:"https://www.debian.org/security/2015/dsa-3207");

  script_tag(name:"summary", value:"The remote host is missing an update for the Debian 'shibboleth-sp2' package(s) announced via the DSA-3207 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"A denial of service vulnerability was found in the Shibboleth (an federated identity framework) Service Provider. When processing certain malformed SAML message generated by an authenticated attacker, the daemon could crash.

For the stable distribution (wheezy), this problem has been fixed in version 2.4.3+dfsg-5+deb7u1.

For the upcoming stable distribution (jessie), this problem has been fixed in version 2.5.3+dfsg-2.

For the unstable distribution (sid), this problem has been fixed in version 2.5.3+dfsg-2.

We recommend that you upgrade your shibboleth-sp2 packages.");

  script_tag(name:"affected", value:"'shibboleth-sp2' package(s) on Debian 7.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  script_tag(name:"deprecated", value:TRUE);

  exit(0);
}

exit(66);